package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Deed</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-d{border-color:var(--bg3);color:var(--cm)}.lic-row{display:flex;align-items:center;gap:.6rem;padding:.5rem;background:var(--bg2);border:1px solid var(--bg3);margin-bottom:.3rem;font-size:.75rem}.lic-key{font-family:var(--mono);color:var(--gold);font-size:.7rem;flex:1}.lic-product{font-weight:600}.lic-status{font-size:.6rem;padding:.1rem .3rem;border-radius:2px}.st-active{background:rgba(74,158,92,.15);color:var(--green)}.st-revoked{background:rgba(196,64,64,.15);color:var(--red)}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number],input[type=date]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Deed</span></h1><button class="btn btn-p" onclick="showNew()">+ License</button></div>
<div class="main"><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function load(){const d=await api('/api/licenses');const lics=d.licenses||[];
document.getElementById('list').innerHTML=lics.length?lics.map(l=>'<div class="lic-row"><span class="lic-product">'+esc(l.product)+'</span><span class="lic-key">'+esc(l.key)+'</span><span class="lic-status st-'+l.status+'">'+l.status+'</span><span style="color:var(--cm);font-size:.65rem">'+esc(l.holder)+'</span><span style="color:var(--cm);font-size:.65rem">'+l.max_seats+' seats</span>'+(l.status==='active'?'<span style="cursor:pointer;font-size:.6rem;color:var(--red)" onclick="revoke(\''+l.id+'\')">revoke</span>':'')+'<span style="cursor:pointer;font-size:.6rem;color:var(--cm)" onclick="del(\''+l.id+'\')">del</span></div>').join(''):'<div class="empty">No licenses yet.</div>'}
async function revoke(id){await api('/api/licenses/'+id+'/revoke',{method:'POST'});load()}
async function del(id){if(!confirm('Delete?'))return;await api('/api/licenses/'+id,{method:'DELETE'});load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New License</h2><label class="fl">Product</label><input type="text" id="nl-prod"><div class="form-row"><div><label class="fl">Holder</label><input type="text" id="nl-hold"></div><div><label class="fl">Email</label><input type="text" id="nl-email"></div></div><div class="form-row"><div><label class="fl">Max Seats</label><input type="number" id="nl-seats" value="1"></div><div><label class="fl">Expires</label><input type="date" id="nl-exp"></div></div><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Generate</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={product:document.getElementById('nl-prod').value,holder:document.getElementById('nl-hold').value,email:document.getElementById('nl-email').value,max_seats:parseInt(document.getElementById('nl-seats').value)||1,expires_at:document.getElementById('nl-exp').value};if(!b.product){alert('Product required');return};const r=await api('/api/licenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});alert('License key: '+r.key);closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
</script></body></html>`
